gatsby submodule
storyblok/storyblok-create-demo pull request #16
Opened 2023-01-17 04:39 UTC by Patrickodey360coder

configuration for gatsby submodules

2023-01-17 12:11 UTC, schabibi1 requested changes
`true` instead of `trued` @Patrickodey360coder

2023-01-17 12:22 UTC, schabibi1 commented
Saw above typo is fixed👍

2023-01-19 06:59 UTC, roberto-butti commented
Great PR @Patrickodey360coder .
IF you want you can add the tutorialLink (for adding a link to the documentation or article.
For example for SvelteKit we are linking the ultimate tutorial:
```
  {
    name: 'Svelte',
    value: 'sveltekit',
    start: 'dev',
    token: 'yourtokenhere',
    config: 'src/routes/+layout.js',
    bridge: 'src/routes/+page.svelte',
    public: 'static',
    port: '5173',
    https: true,
    submodules: true,
    tutorialLink: 'https://www.storyblok.com/tp/the-storyblok-sveltekit-ultimate-tutorial',
  },
```

2023-03-03 08:50 UTC, lisilinhart approved these changes

2023-03-03 08:50 UTC, merged